name: "Setup Rust with Nix"

description: "Sets up Rust and Nix caches and enters the environment specified by the given devshell"

inputs:
  ssh-private-keys:
    description: "SSH deploy keys for private repositories"
    required: true
  devshell:
    description: "Nix devshell to enter"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Compute key for the Cargo registry cache
      shell: bash
      id: cache-key-cargo-registry
      run: |
        set -euo pipefail

        # 1. Compiler environment variables (CARGO_* and RUST_*).
        compiler_env_hash=$((env | grep -E '^(CARGO|RUST)_' | sort || echo "") | sha256sum | cut -d' ' -f1)
        echo "compiler_env_hash: $compiler_env_hash"

        # 2. All Cargo.lock files.
        cargo_lock_hash=$(find . -name 'Cargo.lock' | sort | xargs sha256sum | sha256sum | cut -d' ' -f1)
        echo "cargo_lock_hash: $cargo_lock_hash"

        # 3. The .cargo/config.toml at the root of the repo (if it exists).
        cargo_config_hash=$([ -f ".cargo/config.toml" ] && sha256sum ".cargo/config.toml" | cut -d' ' -f1 || echo "")
        echo "cargo_config_hash: $cargo_config_hash"

        # 4. The rust-toolchain.toml at the root of the repo (if it exists).
        rust_toolchain_hash=$([ -f "rust-toolchain.toml" ] && sha256sum "rust-toolchain.toml" | cut -d' ' -f1 || echo "")
        echo "rust_toolchain_hash: $rust_toolchain_hash"

        # Combine all components into the final cache key.
        combined_key="env:$compiler_env_hash-lock:$cargo_lock_hash-cfg:$cargo_config_hash-tc:$rust_toolchain_hash"
        cache_key=$(echo "$combined_key" | sha256sum | cut -d' ' -f1)
        echo "Cargo registry cache key: $cache_key"
        echo "cache_key=$cache_key" >> $GITHUB_OUTPUT

    - name: Compute key for the build artifacts cache
      shell: bash
      id: cache-key-build-artifacts
      run: |
        set -euo pipefail

        # 1. Cargo registry cache key (from previous step).
        cargo_registry_cache_key="${{ steps.cache-key-cargo-registry.outputs.cache_key }}"
        echo "cargo_registry_cache_key: $cargo_registry_cache_key"

        # 2. All Cargo.toml, and *.rs files.
        source_files_hash=$(find . -name 'Cargo.toml' -o -name '*.rs' | sort | xargs sha256sum | sha256sum | cut -d' ' -f1)
        echo "source_files_hash: $source_files_hash"

        # Combine all components into the final cache key.
        combined_key="reg:$cargo_registry_cache_key-src:$source_files_hash"
        cache_key=$(echo "$combined_key" | sha256sum | cut -d' ' -f1)
        echo "Build artifacts cache key: $cache_key"
        echo "cache_key=$cache_key" >> $GITHUB_OUTPUT

    - name: Cache Cargo registry
      uses: actions/cache@v4
      env:
        CACHE_KEY_PREFIX: cargo-registry-${{ runner.os }}-${{ runner.arch }}
      with:
        path: |
          ~/.cargo/registry/cache/
          ~/.cargo/registry/index/
          ~/.cargo/git/db/
        key: ${{ env.CACHE_KEY_PREFIX }}-${{ steps.cache-key-cargo-registry.outputs.cache_key }}
        restore-keys: |
          ${{ env.CACHE_KEY_PREFIX }}

    - name: Cache build artifacts
      uses: actions/cache@v4
      env:
        CACHE_KEY_PREFIX: cargo-target-${{ runner.os }}-${{ runner.arch }}-${{ github.job }}
      with:
        path: target/
        key: ${{ env.CACHE_KEY_PREFIX }}-${{ github.ref_name }}-${{ steps.cache-key-build-artifacts.outputs.cache_key }}
        # Cache fallback order:
        #
        # 1. last commit on same branch;
        # 2. last commit on main branch;
        # 3. last commit on any branch;
        restore-keys: |
          ${{ env.CACHE_KEY_PREFIX }}-${{ github.ref_name }}
          ${{ env.CACHE_KEY_PREFIX }}-main
          ${{ env.CACHE_KEY_PREFIX }}

    - name: Add deploy keys for private repos
      uses: webfactory/ssh-agent@v0.9.1
      with:
        ssh-private-key: ${{ inputs.ssh-private-keys }}

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Enter Nix devshell
      if: ${{ inputs.devshell != '' }}
      shell: bash
      run: nix run .#nix-develop-gha --accept-flake-config -- ${{ inputs.devshell }} --accept-flake-config
